### ISSUE TITLE
Surreal like Islands, improvements

### ISSUE THREAD

**Issue by YellowOnion** [bravoserver/bravo#123]
I stumbled upon [this](http://codeflow.org/entries/2010/dec/09/minecraft-like-rendering-experiments-in-opengl-4/). this surreal Island seems a lot more "natural" than the current implementation

**Comment by MostAwesomeDude** [comment]
He uses straight-up simplex noise, in three dimensions, with a threshold. We already have a generator, "complex," that does _precisely_ this. You could, if you so desired, add ore support to complex to make it spawn gems in a single step. You could also, if so desired, add an offset to complex to make it generate caves in one step.

If you want to do these things, then patches are welcome. If you want me to improve Bravo in unspecified ways ("natural" is not a specification), then please wait for a few hours and I will probably commit more changes which improve things which have nothing to do with terrain generation. >:3

**Comment by Varriount** [comment]
If you'll notice we have cliff and float generators. I am trying to improve the cliff gen by trying to use an offset comparison instead of generating a new noise map, in order to reduce time taken.  

In addition, the float generator could be rewritten to use  a much more scaled and high resolution contrast noise map to carve away at, and generate comparable results to the article you posted. Currently it uses a seperate noise map, compares the current map with its seperate noise map, and if the two heights are similar, deletes the entire column
 The problem with 3d noise is that its just too slow at the moment in pure python. Feel free to write or adapt a C module that could implement 3d noise, and be as fast as the current simplex generator, as we would be quite grateful.

**Comment by MostAwesomeDude** [comment]
For reasons that I apparently have not stated strongly enough, no, we cannot ship C or Cython, only pure Python.

The "noise" library available on PyPI is completely unsuitable for those reasons, and additionally is missing crucial functionality.
