### ISSUE TITLE
Missing light from digged blocks after reconnect

### ISSUE THREAD

**Issue by squiddy** [bravoserver/bravo#132]
1. Create a world
2. Dig a block
3. Disconnect
4. Connect again

The (now removed) block will be missing light. I assume this happens because the skylight is never regenerated. Digging a block uses set_block() to replace the block, which only updates the heightmap and blocklight.

Regenerating the skylight on that column in set_block() could be a solution. Or just before writing the block to disk.

**Comment by MostAwesomeDude** [comment]
Presumably we need to recalculate per-block lighting. I don't want to think about this yet; Tk and I are going to do a detailed disassembly and documentation of the lighting in a bit and we'll use those results.

**Comment by MostAwesomeDude** [comment]
So, if you look at the current code, it should be obvious that merely regenerating that column's light isn't gonna cut it in the general case. We should probably mark that chunk as needing light regeneration before it's sent out again, in sort of a metadata-on-demand system. (This would be okay because only chunk packets include lightmaps.) See also my comment on that other other bug about heightmap caching and dirtying; maybe all chunk metadata should be damageable. Of course, because of the cost of running those, and the general performance of them, it'd be all-or-nothing, but the fact that we can do these algorithms iteratively is very heartwarming and reassuring in terms of runtime.
