### ISSUE TITLE
Walking through blocks, Spawning blocks on top of, Able to put multiple blocks in the same place.

### ISSUE THREAD

**Issue by Jammer2omega** [bravoserver/bravo#135]
Running 1.2 Easy Bravo Server. No ini changes.
These are the glitches I notice. Not asking for repairs, just bringing them to your attention.

a) Spawning blocks on top of:
When dealing with server replacing blocks, or placing blocks yourself, you can put it on top of yourself. ( http://smg.photobucket.com/albums/v104/Jammer2omega/Minecraft/?action=view&current=StuckInside.jpg ) You can easily move after wards (if you can move).

b) Able to put multiple blocks in same space:
 you can keep clicking on a block and place more then one block in the same spot. (no apparent gain, other then you can place 64 wood blocks into the same spot.) It did seem to cause a glitch where I saw a floating wood block off in the distance, same height and location.

c) Walking through blocks.
When the server goes to replace blocks you can gain a temporary ability to walk through them after they have re-spawned.

**Comment by Varriount** [comment]
For bug a, it is a simple matter of comparing the client position with the block position in the build plugin. B means that the build plugin needs to check if a block is placed at the location already, and not access inventory unless the block is bein placed in air. Because bravo doesn't waste time trying to compare player packets with block placements like Vanilla does, and the client doesn't rely on what it thinks is there to calculate collisions. That last bug could only be fixed with fancy maths and possibly a flier update.

**Comment by MostAwesomeDude** [comment]
The more I reread this, the more it sounds like the server's under heavy load and not responding fast. I'm guessing you're on Windows and don't have Ampoule.

**Comment by MostAwesomeDude** [comment]
Closing due to utter lack of feedback.
