### ISSUE TITLE
Stairs placed backwards and furnace

### ISSUE THREAD

**Issue by dbdii407** [bravoserver/bravo#178]
The title basically sums it up. Upon placing a block of stairs, it will place itself in the opposite direction. Screenshot: http://min.us/mvoLqaZ

There is also a furnace bug. I placed a furnace next to a workbench and the "open slot" moved to the left side.

EDIT: Turns out, all placed stairs end up pointing in the same direction.

**Comment by Varriount** [comment]
To my knowledge, there is currently no stair plugin to handle stair orientation.
At this point, considering how many different blocks use this kind of orientation, I'm wondering if they shouldn't just all be grouped into one plugin for efficiencies and organizations sake.

**Comment by squiddy** [comment]
This can/will be handled by the pre-build stage MostAwesomeDude is considering for plugins.

**Comment by MostAwesomeDude** [comment]
I thought about this earlier. Maybe for blocks that only need orientation metadata on build (torches, ladders, stairs, furnaces, any others?) it would be good to have block data just for this, and then it could be handled in a single built-in part of the Build plugin, rather than as a separate plugin for each block. I think _everybody_ wants ladders that orient properly, and if they don't, they could alter the block data rather than the plugin list.

**Comment by MostAwesomeDude** [comment]
Okay, next time, can we read existing bugs before filing new ones? #69 is this _exact_ bug.

I went ahead and implemented block data for orientable blocks, and switched ladders and torches over to it. I'll switch the others at some point, although I'm not exactly sure what the best way to handle things is, for blocks that can be placed on the floor or ceiling.

**Comment by MostAwesomeDude** [comment]
Closing as furnace orientability is not important enough to warrant a complete realignment hook and the rest of the bug has been handled.
