### ISSUE TITLE
Improve support for chests

### ISSUE THREAD

**Issue by squiddy** [bravoserver/bravo#256]
Right now, chest are loaded from / saved to disk and can be placed. For 1.6 I want (I'll write code for it) players to be able to destroy chests (with its contents spawned as pickups), interact with their inventory and build large chests.

**Comment by MostAwesomeDude** [comment]
Adding to 1.6. I'm totally in favor of this.

**Comment by gtaylor** [comment]
Squiddy, have you started on this yet?

**Comment by squiddy** [comment]
@gtaylor: Yeah, I started. Unfortunately I've been quite busy and didn't get around to continue the work. I had the feeling you wanted to look at it too, am I right?

Sorry for my absence.

**Comment by gtaylor** [comment]
@squiddy: I poked at it, but couldn't figure out the slots argument to the make-window packet. I'm not exactly sure what it is used for, the the protocol docs on MC Coalition's wiki only serve to confuse further. I imagine I've git a knowledge gap about how the protocol fits together as a whole, rather than this being overly complicated.

**Comment by mjevans** [comment]
If chests used to work before, now they don't. :(

**Comment by gtaylor** [comment]
@mjevans I've never seen them working before, don't think they were ever implemented.

**Comment by MostAwesomeDude** [comment]
Recent work on inventories may have closed this bug. Adding to the latest milestone.

**Comment by mcsakoff** [comment]
Can be closed as implemented.

**Comment by MostAwesomeDude** [comment]
Closing in the hope that the recent inventory patches are sufficient for this.
