### ISSUE TITLE
Simulate the Notchian console commands better.

### ISSUE THREAD

**Issue by EntityReborn** [bravoserver/bravo#297]
Currently, it's immediatly obvious that the server isn't an official Notchian server when the user enters /help into the console.
The same goes for /time, but in terms of syntax.

**Comment by EntityReborn** [comment]
mainly, for help:

  command\t\tdoes this

instead of requiring a seperate command for the description.
Maybe instead, allow for the second command to be more detailed (if the plugin supplies more details)

**Comment by MostAwesomeDude** [comment]
We actually switched _from_ that style, to the current style, because there are so many commands that it became unreadable.

We do need to unify it slightly, letting the plugin's docstrings explain the plugin instead of having a separate attribute.

What does Notchian /time look like? Ours is ad-hoc.

**Comment by gtaylor** [comment]
IIRC something like this:

```
/time <set|add> <value>
```

IE:

```
/time add 3000 (adds 3000 seconds to the current time of day)
/time set 0 (sets the time to the first second of the day).
```

**Comment by MostAwesomeDude** [comment]
So, I'm not changing /help, simply because the current help is far more readable than old-school /help. Bravo isn't Notchy and doesn't pretend to be in the command interface. (Bravo also isn't Bukkit, but that's another bug altogether.)

As for /time, I think we could adopt Notchian /time, but I do like the current plethora of available /time options and want to keep them under a new command. /btime, maybe? This could be a good excuse to clean up the horrible wall of code in /time's implementation.

**Comment by gtaylor** [comment]
If you like the current /time's feature set, I'd just keep it and make sure /time has some good error handling to direct people coming from Notchian servers. IMHO, less similar sounding commands = less confusion and less clutter.

**Comment by MostAwesomeDude** [comment]
Opened the very appropriate #360 for /time. Closing this one as invalid.
