### ISSUE TITLE
Falling Sand Block Doesn't Replace Water

### ISSUE THREAD

**Issue by MikePM** [bravoserver/bravo#317]
I guess the same also applies to gravel.
Yeah it just floats above the water (and lava, though this isn't tested).

This time it's a real bug. ;)

**Comment by MostAwesomeDude** [comment]
This should be pretty easy to fix.

Fallables subclass AlphaSandGravel should treat lava, water, springs of both types, as whitespace. Also, ordering should change so that BravoSnow always comes _before_ AlphaSandGravel and correctly evaporates when falling onto water or lava; I wonder if Fallable can handle that?
