### ISSUE TITLE
Digging is broken after 1.8 update.

### ISSUE THREAD

**Issue by mcsakoff** [bravoserver/bravo#349]

**Comment by MostAwesomeDude** [comment]
Specifically, digging works, one-hit KOs work, but giving the client feedback about broken blocks is not happening. The client apparently now expects the server to reply to its attempts to break blocks, otherwise it won't draw the block being damaged and exploding.

Marking for 1.8.1 as this is something people expect when using the Notchy dig policy.

**Comment by mcsakoff** [comment]
Digging in survival works fine. Only creative mode is affected.

**Comment by MostAwesomeDude** [comment]
Survival mode should have the speedy dig policy, right?
