### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by ghost** [bravoserver/bravo#447]
How do install Bravo on OSX? I've been trying to install it for hours, only to fail.

**Comment by edunham** [comment]
Bravo has never been tested on OSX, because no developer on an OSX system has volunteered to add support for it. It's extensively tested in Linux and was supported for a while in Windows, but @brutal-chaos no longer has time to provide Windows support for new versions. 

Your best bet is probably to spin up a Linux virtual machine or dual-boot to Linux. Otherwise, you can try to install Python, Twisted, and all of Bravo's other dependencies on Mac -- we just can't promise it'll work. If you do get it working, please add documentation on how to do it! 

If you run into specific errors, we might be able to help you troubleshoot them if you clearly explain what you were trying to do and share what the error message was. Join us in #bravoserver on irc.freenode.net to talk about it!
