### ISSUE TITLE
Torch checking

### ISSUE THREAD

**Issue by actown** [bravoserver/bravo#88]
Check to see if torches need to be broken and then dropped if they are not attached to a block.

**Comment by MostAwesomeDude** [comment]
Could be easily handled by adding a dig_hook to Torch. Wonder if there's a better way to do this?

**Comment by Varriount** [comment]
Well, we could have an entire physics system which checks the blocks around each block modification a player makes. say that all the blocks around a block the player places was checked, and a sand block that needed to fall was found. That blocks would be acted upon, then the coordinates around where it was would be checked. This would go on, and while it might take more calculation, would be far more robust than the current system

**Comment by barsch** [comment]
for player building it just needs a check if there is already a torch block at this position - if not: build using metadata - if so: do nothing - player has to remove torch first in order to build a new one (which goes via standard dig hook) ...

for falling sand/gravel it will get complicated: but something triggers the falling block, so the _standard_ dig hook has to check whats above and eventually trigger  a "falling" block by digging it - all falling blocks must check on the way down of they can destroy anything (deleting it) and if they can trigger a block above them

**Comment by MostAwesomeDude** [comment]
Varriount: No. That's the stupid recursive logic that make's Notch's TNT slow. Just write down the coords of affected blocks, and check them on the next iteration.

The dig hooks are currently very modular and disconnected. I'm okay with retooling them, but I'd like to hear _why_ it'll be a win and not just code shuffling.

**Comment by kingofkya** [comment]
I had this issue also, but removing and replacing touch fixed it until next reload. Where it did the same thing. In my case it was a single cube straight down.

**Comment by MostAwesomeDude** [comment]
01fa09d32aec7ca9bcecb1bee6f062c93431ad5f fixes this bug as-is. However, as noted, there is a definite possibility for rewriting the signature and semantics of dig_hook. If people want to talk about it again, please open a new issue instead of continuing to co-opt this one.
